version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./js
    volumes:
      - ./js:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  pgdata:
